# Generated by Django 3.2.25 on 2024-08-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trainee_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
